// 100 Word Search Levels - Words get progressively harder
export const WORD_SEARCH_LEVELS = [
  // Level 1-10: Easy 3-4 letter words (School items, colors)
  { level: 1, words: ['PEN', 'BOOK', 'DESK', 'BAG'], theme: 'School Items' },
  { level: 2, words: ['RED', 'BLUE', 'PINK', 'GREEN'], theme: 'Colors' },
  { level: 3, words: ['CAT', 'DOG', 'BIRD', 'FISH'], theme: 'Pets' },
  { level: 4, words: ['SUN', 'MOON', 'STAR', 'SKY'], theme: 'Sky' },
  { level: 5, words: ['HAT', 'SHOE', 'COAT', 'SOCK'], theme: 'Clothes' },
  { level: 6, words: ['TREE', 'LEAF', 'WOOD', 'BARK'], theme: 'Nature' },
  { level: 7, words: ['BALL', 'DOLL', 'TOY', 'GAME'], theme: 'Toys' },
  { level: 8, words: ['MILK', 'WATER', 'JUICE', 'TEA'], theme: 'Drinks' },
  { level: 9, words: ['CAKE', 'BREAD', 'RICE', 'PIE'], theme: 'Food' },
  { level: 10, words: ['HAND', 'FOOT', 'NOSE', 'EARS'], theme: 'Body Parts' },

  // Level 11-20: Easy 4-5 letter words (Animals, fruits)
  { level: 11, words: ['LION', 'TIGER', 'BEAR', 'WOLF'], theme: 'Wild Animals' },
  { level: 12, words: ['APPLE', 'GRAPE', 'LEMON', 'MANGO'], theme: 'Fruits' },
  { level: 13, words: ['HORSE', 'SHEEP', 'GOAT', 'DEER'], theme: 'Farm Animals' },
  { level: 14, words: ['HOUSE', 'DOOR', 'ROOF', 'WALL'], theme: 'House Parts' },
  { level: 15, words: ['CHAIR', 'TABLE', 'LAMP', 'RUG'], theme: 'Furniture' },
  { level: 16, words: ['RIVER', 'LAKE', 'POND', 'SEA'], theme: 'Water Bodies' },
  { level: 17, words: ['PLANE', 'TRAIN', 'BOAT', 'BUS'], theme: 'Transport' },
  { level: 18, words: ['SMILE', 'LAUGH', 'HAPPY', 'JOY'], theme: 'Happy Words' },
  { level: 19, words: ['WINTER', 'SPRING', 'SUMMER', 'FALL'], theme: 'Seasons' },
  { level: 20, words: ['DOCTOR', 'TEACHER', 'FARMER', 'CHEF'], theme: 'Jobs' },

  // Level 21-30: Medium 5-6 letter words
  { level: 21, words: ['GARDEN', 'FLOWER', 'GRASS', 'PLANT'], theme: 'Garden' },
  { level: 22, words: ['CIRCLE', 'SQUARE', 'OVAL', 'HEART'], theme: 'Shapes' },
  { level: 23, words: ['PIANO', 'GUITAR', 'DRUM', 'FLUTE'], theme: 'Instruments' },
  { level: 24, words: ['YELLOW', 'ORANGE', 'PURPLE', 'BROWN'], theme: 'More Colors' },
  { level: 25, words: ['FAMILY', 'MOTHER', 'FATHER', 'BABY'], theme: 'Family' },
  { level: 26, words: ['SCHOOL', 'CLASS', 'PUPIL', 'GRADE'], theme: 'School' },
  { level: 27, words: ['BUTTER', 'CHEESE', 'CREAM', 'YOGURT'], theme: 'Dairy' },
  { level: 28, words: ['CARROT', 'ONION', 'PEPPER', 'CORN'], theme: 'Vegetables' },
  { level: 29, words: ['TURTLE', 'RABBIT', 'MOUSE', 'SNAKE'], theme: 'Small Animals' },
  { level: 30, words: ['MARKET', 'STORE', 'SHOP', 'MALL'], theme: 'Shopping' },

  // Level 31-40: Harder 6-7 letter words
  { level: 31, words: ['ELEPHANT', 'GIRAFFE', 'MONKEY', 'DONKEY'], theme: 'Zoo Animals' },
  { level: 32, words: ['BANANA', 'ORANGE', 'CHERRY', 'COCONUT'], theme: 'Tropical Fruits' },
  { level: 33, words: ['BICYCLE', 'SCOOTER', 'SKATE', 'ROLLER'], theme: 'Wheels' },
  { level: 34, words: ['COUNTRY', 'CITY', 'TOWN', 'VILLAGE'], theme: 'Places' },
  { level: 35, words: ['KITCHEN', 'BEDROOM', 'BATHROOM', 'GARAGE'], theme: 'Rooms' },
  { level: 36, words: ['MORNING', 'NOON', 'NIGHT', 'EVENING'], theme: 'Time of Day' },
  { level: 37, words: ['HOLIDAY', 'VACATION', 'PICNIC', 'PARTY'], theme: 'Fun Times' },
  { level: 38, words: ['OCEAN', 'BEACH', 'ISLAND', 'SAND'], theme: 'Beach' },
  { level: 39, words: ['FOREST', 'JUNGLE', 'DESERT', 'MOUNTAIN'], theme: 'Landscapes' },
  { level: 40, words: ['BROTHER', 'SISTER', 'COUSIN', 'AUNTIE'], theme: 'Relatives' },

  // Level 41-50: Challenge 7-8 letter words
  { level: 41, words: ['AIRPORT', 'HARBOR', 'STATION', 'DEPOT'], theme: 'Travel Hubs' },
  { level: 42, words: ['HOSPITAL', 'CLINIC', 'PHARMACY', 'DENTIST'], theme: 'Health' },
  { level: 43, words: ['LIBRARY', 'MUSEUM', 'THEATER', 'STADIUM'], theme: 'Buildings' },
  { level: 44, words: ['REPTILE', 'MAMMAL', 'BIRD', 'INSECT'], theme: 'Animal Types' },
  { level: 45, words: ['VOLCANO', 'VALLEY', 'CANYON', 'GLACIER'], theme: 'Geography' },
  { level: 46, words: ['PLANETS', 'GALAXY', 'COMET', 'METEOR'], theme: 'Space' },
  { level: 47, words: ['CARNIVAL', 'FESTIVAL', 'PARADE', 'FAIR'], theme: 'Celebrations' },
  { level: 48, words: ['PUZZLE', 'RIDDLE', 'MAZE', 'GAME'], theme: 'Brain Games' },
  { level: 49, words: ['MYSTERY', 'SECRET', 'PUZZLE', 'CLUE'], theme: 'Mystery' },
  { level: 50, words: ['CHAMPION', 'VICTORY', 'SUCCESS', 'WINNER'], theme: 'Champions' },

  // Level 51-60: Advanced vocabulary
  { level: 51, words: ['DINOSAUR', 'DRAGON', 'UNICORN', 'PHOENIX'], theme: 'Mythical Creatures' },
  { level: 52, words: ['DIAMOND', 'RUBY', 'EMERALD', 'SAPPHIRE'], theme: 'Gems' },
  { level: 53, words: ['RAINBOW', 'CLOUD', 'THUNDER', 'LIGHTNING'], theme: 'Weather' },
  { level: 54, words: ['PAINTER', 'SCULPTOR', 'MUSICIAN', 'DANCER'], theme: 'Artists' },
  { level: 55, words: ['SPACESHIP', 'ROCKET', 'SATELLITE', 'SHUTTLE'], theme: 'Space Travel' },
  { level: 56, words: ['ADVENTURE', 'JOURNEY', 'VOYAGE', 'EXPEDITION'], theme: 'Travel' },
  { level: 57, words: ['CROCODILE', 'ALLIGATOR', 'LIZARD', 'GECKO'], theme: 'Reptiles' },
  { level: 58, words: ['BUTTERFLY', 'DRAGONFLY', 'LADYBUG', 'BEETLE'], theme: 'Insects' },
  { level: 59, words: ['ASTRONAUT', 'PILOT', 'SAILOR', 'DRIVER'], theme: 'Vehicle Operators' },
  { level: 60, words: ['TREASURE', 'GOLD', 'SILVER', 'JEWELS'], theme: 'Treasure' },

  // Level 61-70: Science and nature
  { level: 61, words: ['CHEMISTRY', 'PHYSICS', 'BIOLOGY', 'SCIENCE'], theme: 'Sciences' },
  { level: 62, words: ['HURRICANE', 'TORNADO', 'TSUNAMI', 'EARTHQUAKE'], theme: 'Natural Disasters' },
  { level: 63, words: ['SUNFLOWER', 'ROSE', 'DAISY', 'LILY'], theme: 'Flowers' },
  { level: 64, words: ['WHISPER', 'SHOUT', 'MURMUR', 'ECHO'], theme: 'Sounds' },
  { level: 65, words: ['CASTLE', 'PALACE', 'FORTRESS', 'TOWER'], theme: 'Fortifications' },
  { level: 66, words: ['UMBRELLA', 'RAINCOAT', 'BOOTS', 'COAT'], theme: 'Rain Gear' },
  { level: 67, words: ['COMPASS', 'MAP', 'TELESCOPE', 'BINOCULARS'], theme: 'Exploration Tools' },
  { level: 68, words: ['BACTERIA', 'VIRUS', 'GERM', 'CELL'], theme: 'Microorganisms' },
  { level: 69, words: ['ECLIPSE', 'SOLSTICE', 'EQUINOX', 'PHASE'], theme: 'Astronomy' },
  { level: 70, words: ['DICTIONARY', 'ATLAS', 'ALMANAC', 'ENCYCLOPEDIA'], theme: 'Reference Books' },

  // Level 71-80: Food and cooking
  { level: 71, words: ['SANDWICH', 'BURGER', 'HOTDOG', 'PIZZA'], theme: 'Fast Food' },
  { level: 72, words: ['SPAGHETTI', 'LASAGNA', 'RAVIOLI', 'MACARONI'], theme: 'Pasta' },
  { level: 73, words: ['PANCAKE', 'WAFFLE', 'CROISSANT', 'DONUT'], theme: 'Breakfast' },
  { level: 74, words: ['CUCUMBER', 'ZUCCHINI', 'PUMPKIN', 'SQUASH'], theme: 'Squash Family' },
  { level: 75, words: ['CHOCOLATE', 'CARAMEL', 'BUTTERSCOTCH', 'FUDGE'], theme: 'Sweets' },
  { level: 76, words: ['SAUSAGE', 'BACON', 'HAM', 'SALAMI'], theme: 'Meats' },
  { level: 77, words: ['CINNAMON', 'NUTMEG', 'GINGER', 'CLOVE'], theme: 'Spices' },
  { level: 78, words: ['BARBECUE', 'GRILL', 'SMOKE', 'ROAST'], theme: 'Cooking Methods' },
  { level: 79, words: ['BLENDER', 'MIXER', 'GRATER', 'WHISK'], theme: 'Kitchen Tools' },
  { level: 80, words: ['RESTAURANT', 'CAFE', 'BISTRO', 'DINER'], theme: 'Eateries' },

  // Level 81-90: Sports and activities
  { level: 81, words: ['BASEBALL', 'FOOTBALL', 'BASKETBALL', 'VOLLEYBALL'], theme: 'Team Sports' },
  { level: 82, words: ['SWIMMING', 'DIVING', 'SURFING', 'SAILING'], theme: 'Water Sports' },
  { level: 83, words: ['GYMNASTICS', 'DANCING', 'SKATING', 'SKIING'], theme: 'Individual Sports' },
  { level: 84, words: ['TENNIS', 'BADMINTON', 'SQUASH', 'RACQUETBALL'], theme: 'Racket Sports' },
  { level: 85, words: ['ARCHERY', 'FENCING', 'WRESTLING', 'BOXING'], theme: 'Combat Sports' },
  { level: 86, words: ['CHECKERS', 'CHESS', 'DOMINOES', 'CARDS'], theme: 'Board Games' },
  { level: 87, words: ['FISHING', 'CAMPING', 'HIKING', 'CLIMBING'], theme: 'Outdoor Activities' },
  { level: 88, words: ['MARATHON', 'SPRINT', 'RELAY', 'RACE'], theme: 'Running' },
  { level: 89, words: ['MEDAL', 'TROPHY', 'CUP', 'PRIZE'], theme: 'Awards' },
  { level: 90, words: ['STADIUM', 'ARENA', 'COURT', 'FIELD'], theme: 'Sports Venues' },

  // Level 91-100: Master level
  { level: 91, words: ['PENINSULA', 'ARCHIPELAGO', 'ISTHMUS', 'FJORD'], theme: 'Landforms' },
  { level: 92, words: ['CHAMELEON', 'OCTOPUS', 'SQUID', 'JELLYFISH'], theme: 'Color Changers' },
  { level: 93, words: ['TRAMPOLINE', 'SEESAW', 'SWINGS', 'SLIDE'], theme: 'Playground' },
  { level: 94, words: ['CALCULATOR', 'COMPUTER', 'TABLET', 'PHONE'], theme: 'Technology' },
  { level: 95, words: ['SUBMARINE', 'BATTleship', 'Cruiser', 'DESTROYER'], theme: 'Warships' },
  { level: 96, words: ['HElicopter', 'AIRPLANE', 'BLIMP', 'GLIDER'], theme: 'Aircraft' },
  { level: 97, words: ['GRANDMA', 'GRANDPA', 'GRANDSON', 'GRANDDAUGHTER'], theme: 'Grandparents' },
  { level: 98, words: ['FIRETRUCK', 'AMBULANCE', 'POLICE', 'TOWTRUCK'], theme: 'Service Vehicles' },
  { level: 99, words: ['DOLPHIN', 'WHALE', 'SHARK', 'SEAL'], theme: 'Sea Creatures' },
  { level: 100, words: ['EXCELLENT', 'BRILLIANT', 'AMAZING', 'SPECTACULAR'], theme: 'Compliments' }
]
